routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login','Admin\LoginController@index')->name('login');
Route::post('login','Admin\LoginController@checkLogin')->name('login.check-login');
Route::get('register','Admin\RegistrationController@index')->name('register');
Route::post('register','Admin\RegistrationController@store')->name('register.store');

// Forgot Password
Route::get('forgot-password/', 'Admin\ForgotPasswordController@index')->name('forgot-password.index');
Route::get('forgot-password/{email}/{token}', 'Admin\ForgotPasswordController@showResetPasswordForm')->name('forgot-password.reset');
Route::post('forgot-password/email', 'Admin\ForgotPasswordController@email')->name('forgot-password.email');
Route::post('forgot-password/reset-password', 'Admin\ForgotPasswordController@resetPassword')->name('forgot-password.reset-password');
	

Route::middleware('auth')->namespace('Admin')->group(function(){

	Route::get('home','HomeController@index')->name('home');

	Route::resource('profile', 'ProfileController');
    Route::post('profile/change-password', 'ProfileController@changePassword')->name('profile.change-password');

    Route::post('user/get-all', 'UserController@getAll')->name('user.get-all');
	Route::get('user/status/{id}', 'UserController@updateStatus')->name('user.status');
	Route::get('user/edit-to-access/{id}', 'UserController@updateEditToAccess')->name('user.edit_to_access');
    Route::resource('user', 'UserController');

	Route::get('/logout', function () {
		Auth::logout();
	    return redirect()->route('login');
	})->name('logout');
});

Route::get('clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    return "Cache is cleared";
});

resources/views/admin/layouts/include/footer.blade.php
<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-light">
  <p class="clearfix mb-0"><span class="float-md-start d-block d-md-inline-block mt-25">COPYRIGHT  &copy; {{ date('Y') }}<a class="ms-25">Pixinvent</a><span class="d-none d-sm-inline-block">, All rights Reserved</span></span></p>
</footer>
<button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>

resources/views/admin/layouts/include/head.blade.php
<link rel="apple-touch-icon" href="{{ asset('assets') }}/app-assets/images/ico/apple-icon-120.html">
<link rel="shortcut icon" type="image/x-icon" href="https://pixinvent.com/demo/vuexy-html-bootstrap-admin-template/app-assets/images/ico/favicon.ico">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">

<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/vendors/css/vendors.min.css">
<!-- END: Vendor CSS-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>

<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="{{asset('assets/app-assets/vendors/css/vendors.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/app-assets/vendors/css/tables/datatable/dataTables.bootstrap5.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/app-assets/vendors/css/tables/datatable/responsive.bootstrap5.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/app-assets/vendors/css/tables/datatable/buttons.bootstrap5.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/app-assets/vendors/css/tables/datatable/rowGroup.bootstrap5.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css')}}">

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/bootstrap-extended.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/colors.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/components.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/themes/dark-layout.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/themes/bordered-layout.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/themes/semi-dark-layout.min.css">

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/app-assets/css/core/menu/menu-types/vertical-menu.min.css">
<!-- END: Page CSS-->

<!-- BEGIN: Custom CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/assets/css/style.css">
<!-- END: Custom CSS-->

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css">

<style>
  	.is-invalid{
    	color: red !important;
  	}

  	.required{
        color: red !important;
    }

  	.header-navbar .navbar-container ul.navbar-nav li.dropdown-user .dropdown-menu {
	    width: 14rem;
	    margin-top: 10px;
	}
</style>
    
@stack('css')

resources/views/admin/layouts/include/header.blade.php
<!-- BEGIN: Header-->
<nav class="header-navbar navbar navbar-expand-lg align-items-center floating-nav navbar-light navbar-shadow container-xxl">
  <div class="navbar-container d-flex content">
    <div class="bookmark-wrapper d-flex align-items-center">
      <ul class="nav navbar-nav d-xl-none">
        <li class="nav-item"><a class="nav-link menu-toggle" href="#"><i class="ficon" data-feather="menu"></i></a></li>
      </ul>
    </div>
    <ul class="nav navbar-nav align-items-center ms-auto">
      
      <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-style"><i class="ficon" data-feather="moon"></i></a></li>
      
      
      <li class="nav-item dropdown dropdown-user"><a class="nav-link dropdown-toggle dropdown-user-link" id="dropdown-user" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="user-nav d-sm-flex d-none">
            <span class="user-name fw-bolder">{{ @Auth::user()->name ?? ""}}</span><span class="user-status">Admin</span>
          </div>

          <span class="avatar"><img class="round" src="{{ asset('assets') }}/app-assets/images/portrait/small/avatar-s-11.jpg" alt="avatar" height="40" width="40"><span class="avatar-status-online"></span></span></a>

        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown-user">
          <a class="dropdown-item" href="{{ route('profile.index') }}"><i class="me-50" data-feather="user"></i> Profile</a>
          <a class="dropdown-item" href="{{ route('profile.index') }}"><i class="me-50" data-feather="lock"></i> Change Password</a>
          <a class="dropdown-item" href="{{ route('logout') }}"><i class="me-50" data-feather="power"></i> Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!-- END: Header-->

resources/views/admin/layouts/include/script.blade.php
<!-- BEGIN: Vendor JS-->
<script src="{{ asset('assets') }}/app-assets/vendors/js/vendors.min.js"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="{{ asset('assets') }}/app-assets/js/core/app-menu.min.js"></script>
<script src="{{ asset('assets') }}/app-assets/js/core/app.min.js"></script>
<script src="{{ asset('assets') }}/app-assets/js/scripts/customizer.min.js"></script>
<!-- END: Theme JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>

<script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>    

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>

<script src="{{asset('assets/app-assets/js/common/function.js')}}"></script>

<script>
  $(window).on('load',  function(){
    if (feather) {
      feather.replace({ width: 14, height: 14 });
    }
  })
</script>

@stack('script')

resources/views/admin/layouts/include/sidebar.blade.php
<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
  <div class="navbar-header">
    <ul class="nav navbar-nav flex-row">
      <li class="nav-item me-auto"><a class="navbar-brand" href="{{ route('home') }}"><span class="brand-logo">
            <svg viewbox="0 0 139 95" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="24">
              <defs>
                <lineargradient id="linearGradient-1" x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%">
                  <stop stop-color="#000000" offset="0%"></stop>
                  <stop stop-color="#FFFFFF" offset="100%"></stop>
                </lineargradient>
                <lineargradient id="linearGradient-2" x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%">
                  <stop stop-color="#EEEEEE" stop-opacity="0" offset="0%"></stop>
                  <stop stop-color="#FFFFFF" offset="100%"></stop>
                </lineargradient>
              </defs>
              <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <g id="Artboard" transform="translate(-400.000000, -178.000000)">
                  <g id="Group" transform="translate(400.000000, 178.000000)">
                    <path class="text-primary" id="Path" d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z" style="fill:currentColor"></path>
                    <path id="Path1" d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z" fill="url(#linearGradient-1)" opacity="0.2"></path>
                    <polygon id="Path-2" fill="#000000" opacity="0.049999997" points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325"></polygon>
                    <polygon id="Path-21" fill="#000000" opacity="0.099999994" points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338"></polygon>
                    <polygon id="Path-3" fill="url(#linearGradient-2)" opacity="0.099999994" points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288"></polygon>
                  </g>
                </g>
              </g>
            </svg></span>
          <h2 class="brand-text">FamilyTree</h2></a></li>
      <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pe-0" data-bs-toggle="collapse"><i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i></a></li>
    </ul>
  </div>
  <div class="shadow-bottom"></div>
  <div class="main-menu-content">
    <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
      
      <li class="nav-item {{ in_array(Route::currentRouteName(), ['home']) ? "active" : "" }}"><a class="d-flex align-items-center" href="{{ route('home') }}"><i data-feather="home"></i><span class="menu-title text-truncate" data-i18n="Dashboard">Dashboard</span></a>
      </li>

      <li class="nav-item {{ in_array(Route::currentRouteName(), ['user.index','user.create','user.edit','user.show']) ? "active" : "" }}"><a class="d-flex align-items-center" href="{{ route('user.index') }}"><i data-feather="users"></i><span class="menu-title text-truncate" data-i18n="Users">Users</span></a>
      </li>

      <li class="nav-item {{ in_array(Route::currentRouteName(), ['profile.index']) ? "active" : "" }}"><a class="d-flex align-items-center" href="{{ route('profile.index') }}"><i data-feather="user"></i><span class="menu-title text-truncate" data-i18n="Profile">Profile</span></a>
      </li>
      
    </ul>
  </div>
</div>
<!-- END: Main Menu-->