routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login','Admin\LoginController@index')->name('login');
Route::post('login','Admin\LoginController@checkLogin')->name('login.check-login');
Route::get('register','Admin\RegistrationController@index')->name('register');
Route::post('register','Admin\RegistrationController@store')->name('register.store');

// Forgot Password
Route::get('forgot-password/', 'Admin\ForgotPasswordController@index')->name('forgot-password.index');
Route::get('forgot-password/{email}/{token}', 'Admin\ForgotPasswordController@showResetPasswordForm')->name('forgot-password.reset');
Route::post('forgot-password/email', 'Admin\ForgotPasswordController@email')->name('forgot-password.email');
Route::post('forgot-password/reset-password', 'Admin\ForgotPasswordController@resetPassword')->name('forgot-password.reset-password');
	

Route::middleware('auth')->namespace('Admin')->group(function(){

	Route::get('home','HomeController@index')->name('home');

	Route::resource('profile', 'ProfileController');
    Route::post('profile/change-password', 'ProfileController@changePassword')->name('profile.change-password');

    Route::post('user/get-all', 'UserController@getAll')->name('user.get-all');
	Route::get('user/status/{id}', 'UserController@updateStatus')->name('user.status');
	Route::get('user/edit-to-access/{id}', 'UserController@updateEditToAccess')->name('user.edit_to_access');
    Route::resource('user', 'UserController');

	Route::get('/logout', function () {
		Auth::logout();
	    return redirect()->route('login');
	})->name('logout');
});

Route::get('clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    return "Cache is cleared";
});

app/Http/Controllers/Admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use Hash;
use Validator;
use App\Models\User;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.profile.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $rules = array(
                    'name' => 'required|string|max:185',
                    'email' => 'required|max:185|unique:users,email,'.Auth::id().',id,deleted_at,NULL|regex:/(.+)@(.+)\.(.+)/i',
                    'mobile_no' => 'required|numeric|digits:10|unique:users,mobile_no,'.Auth::id().',id,deleted_at,NULL',
                );

        $validator = Validator::make($input, $rules);

        if ($validator->fails()) {
            $response = ['status'=>false,'message'=>$validator->errors()->first()];
        }else{
            $user = User::find(Auth::id());

            $user->fill($input)->save();

            $response = ['status'=>true,'message'=>'Profile details update successfully !'];
        }

        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function changePassword(Request $request){
        $input = $request->all();

        $rules = array(
                    'current_password' => 'required|string',
                    'new_password' => 'required|string|min:8',
                    'confirm_password' => 'required|string|min:8|same:new_password',
                );
        $validator = Validator::make($input, $rules);

        if ($validator->fails()) {
            $response = ['status'=>false,'message'=>$validator->errors()->first()];
        }else{
            $user = User::find(Auth::id());
            if(Hash::check($input['current_password'], $user->password)){
                $user->password = Hash::make($input['confirm_password']);
                $user->save();

                $response = ['status'=>true,'message'=>'Password change successfully !'];
            }else{
                $response = ['status'=>false,'message'=>'Current password is wrong !'];
            }
        }

        return $response;
    }
}

resources/views/admin/profile/index.blade.php
@extends('admin.layouts.master')

@section('title','Profile')

@section('content')

<div class="content-header row">
  <div class="content-header-left col-md-9 col-12 mb-2">
    <div class="row breadcrumbs-top">
      <div class="col-12">
        <h2 class="">Profile</h2>
      </div>
    </div>
  </div>
</div>


<div class="content-body"><!-- Validation -->
  <section class="bs-validation">
    <div class="row">
      <div class="col-md-6 col-6">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Update Profile</h4>
          </div>
          <div class="card-body">
            <form id="myProfileForm" >
              @csrf
              <div class="row mb-1">
                <div class="col-md-12">
                  <label>Name</label>
                  <input type="text" name="name" placeholder="Enter name" class="form-control" value="{{ @Auth::user()->name }}" >
                </div>
              </div>

              <div class="row mb-1">
                <div class="col-md-12">
                  <label>Email</label>
                  <input type="email" name="email" placeholder="Enter email" class="form-control" value="{{ @Auth::user()->email }}" >
                </div>
              </div>

              <div class="row mb-1">
                <div class="col-md-12">
                  <label>Mobile No</label>
                  <input type="text" name="mobile_no" placeholder="Enter mobile no" class="form-control" value="{{ @Auth::user()->mobile_no }}" >
                </div>
              </div>

              <div class="form-group row text-right">
                <div class="col col-sm-10 col-lg-9">
                  <button type="submit" class="btn btn-space btn-primary">Update</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-6">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Change Password</h4>
          </div>
          <div class="card-body">
            <form id="myPasswordForm" >
              @csrf
              <div class="row mb-1">
                <div class="col-md-12">
                  <label>Current Password</label>
                  <input type="password" name="current_password" placeholder="Enter current password" class="form-control">
                </div>
              </div>

              <div class="row mb-1">
                <div class="col-md-12">
                  <label>New Password</label>
                  <input type="password" name="new_password" id="new_password" placeholder="Enter new password" class="form-control">
                </div>
              </div>

              <div class="row mb-1">
                <div class="col-md-12">
                  <label>Confirm Password</label>
                  <input type="password" name="confirm_password" placeholder="Enter confirm password" class="form-control">
                </div>
              </div>

              <div class="form-group row text-right">
                <div class="col col-sm-10 col-lg-9">
                  <button type="submit" class="btn btn-space btn-primary">Update</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection

@push('script')
<script>
  $(document).ready(function() {
    $('body').on("submit", "#myProfileForm", function (e) {
      e.preventDefault();
      var validator = validate_profile_form();
      if (validator.form() != false) {
        $.ajax({
          url: "{{route('profile.store')}}",
          type: "POST",
          data: new FormData($("#myProfileForm")[0]),
          async: false,
          processData: false,
          contentType: false,
          success: function (data) {
            if (data.status) {
              toast_success(data.message)
              setTimeout(function(){
                  window.location.reload();
              },1500)
            } else {
              toast_error(data.message);
            }
          },
          error: function () {
            toast_error("Something went to wrong !");
          },
        });
      }
    });

    function validate_profile_form(){
      var validator = $("#myProfileForm").validate({
          errorClass: "is-invalid",
          validClass: "is-valid",
          rules: {
              name:{
                required: true,
                maxlength: 185,
              },
              email:{
                required:true,
                maxlength: 185,
              },
              mobile_no:{
                required:true,
                digits:true,
                minlength:10,
                maxlength:10,
              }
          },
          messages: {
              
              name:{
                  required: "Please enter name.",
              },
              email:{
                  required:"Please enter email.",
              },
              phone_number:{
                  required:"Please enter phone number.",
                  digits:"Please enter valid phone number.",
                  minlength:"Please enter valid phone number.",
                  maxlength:"Please enter valid phone number.",
              }
          },
      });

      return validator;
    }


    $('body').on("submit", "#myPasswordForm", function (e) {
      e.preventDefault();
      var validator = validate_password_form();
      if (validator.form() != false) {
        $.ajax({
          url: "{{route('profile.change-password')}}",
          type: "POST",
          data: new FormData($("#myPasswordForm")[0]),
          async: false,
          processData: false,
          contentType: false,
          success: function (data) {
            if (data.status) {
              toast_success(data.message)
              setTimeout(function(){
                  window.location.reload();
              },1500)
            } else {
              toast_error(data.message);
            }
          },
          error: function () {
            toast_error("Something went to wrong !");
          },
        });
      }
    });

    function validate_password_form(){
      var validator = $("#myPasswordForm").validate({
          errorClass: "is-invalid",
          validClass: "is-valid",
          rules: {
              current_password:{
                required:true,
                minlength:8,
              },
              new_password:{
                required:true,
                minlength:8,
              },
              confirm_password:{
                required:true,
                minlength:8,
                equalTo : "#new_password"
              }
          },
          messages: {
              current_password:{
                required:'Please enter current password.',
                minlength:'Please enter current password greater than 8 digits',
              },
              new_password:{
                required:'Please enter new password.',
                minlength:'Please enter new password greater than 8 digits',
              },
              confirm_password:{
                required:'Please enter confirm password.',
                minlength:'Please enter confirm password greater than 8 digits',
                equalTo : "Enter confirm password not same as password !"
              }
          },
      });

      return validator;
    }    
  });
</script>
@endpush